apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: nginx-mct-dev
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: mct-pvc-dev-claim
  containers:
    - name: mct-container
      image: nginx
      volumeMounts:
        - mountPath: "/tmp/devdata"
          name: task-pv-storage