apiVersion: v1
kind: Pod
metadata:
  namespace: abi
  name: nginx-mct-abi
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: mct-pvc-abi-claim
  containers:
    - name: mct-container
      image: nginx
      volumeMounts:
        - mountPath: "/tmp/devdata"
          name: task-pv-storage