apiVersion: v1
kind: PersistentVolume
metadata:
  Namespace: default
  name: persist-pv
  
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/storage/data"