apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dialog
  name: dialog
spec:
  containers:
  - image: bims15/dialog:latest
    name: dialog
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
