apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dialog3
  name: dialog3
spec:
  containers:
  - image: bims15/dialog3:latest
    name: dialog3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
