apiVersion: v1
kind: Pod
metadata: 
  name: secret-pod
spec:
  containers:
  - name: secret-test-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/config/secret
  volumes:
  - name: secret-volume
    secret:
      secretName: data-secret